version: '3'
services:
  django:
    build:
      context: django
      dockerfile: Dockerfile
    image: pgarchives
    container_name: django-server
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=postgresqldb
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8888:8888
    volumes:
      - .:/app
    depends_on:
      - postgresqldb
    networks:
      - app-network
    command:
      - /bin/sh
      - -c
      - |
        python manage.py runserver 0.0.0.0:8888
  postgresqldb:
    image: postgres
    container_name: postgresqldb
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRESQL_DATABASE=$DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - dbdata:/bitnami/postgresql
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
